import { City, Guide, Product, Restaurant } from "./types";

const cityRows = [
  ["seoul", "Seoul", "Seoul Special City"],
  ["busan", "Busan", "Busan Metropolitan City"],
  ["daegu", "Daegu", "Daegu Metropolitan City"],
  ["incheon", "Incheon", "Incheon Metropolitan City"],
  ["gwangju", "Gwangju", "Gwangju Metropolitan City"],
  ["daejeon", "Daejeon", "Daejeon Metropolitan City"],
  ["ulsan", "Ulsan", "Ulsan Metropolitan City"],
  ["sejong", "Sejong", "Sejong Special Self-Governing City"],
  ["suwon", "Suwon", "Gyeonggi-do"],
  ["seongnam", "Seongnam", "Gyeonggi-do"],
  ["uijeongbu", "Uijeongbu", "Gyeonggi-do"],
  ["anyang", "Anyang", "Gyeonggi-do"],
  ["bucheon", "Bucheon", "Gyeonggi-do"],
  ["gwangmyeong", "Gwangmyeong", "Gyeonggi-do"],
  ["pyeongtaek", "Pyeongtaek", "Gyeonggi-do"],
  ["dongducheon", "Dongducheon", "Gyeonggi-do"],
  ["ansan", "Ansan", "Gyeonggi-do"],
  ["goyang", "Goyang", "Gyeonggi-do"],
  ["gwacheon", "Gwacheon", "Gyeonggi-do"],
  ["guri", "Guri", "Gyeonggi-do"],
  ["namyangju", "Namyangju", "Gyeonggi-do"],
  ["osan", "Osan", "Gyeonggi-do"],
  ["siheung", "Siheung", "Gyeonggi-do"],
  ["gunpo", "Gunpo", "Gyeonggi-do"],
  ["uiwang", "Uiwang", "Gyeonggi-do"],
  ["hanam", "Hanam", "Gyeonggi-do"],
  ["yongin", "Yongin", "Gyeonggi-do"],
  ["paju", "Paju", "Gyeonggi-do"],
  ["icheon", "Icheon", "Gyeonggi-do"],
  ["anseong", "Anseong", "Gyeonggi-do"],
  ["gimpo", "Gimpo", "Gyeonggi-do"],
  ["hwaseong", "Hwaseong", "Gyeonggi-do"],
  ["gwangju-gyeonggi", "Gwangju", "Gyeonggi-do"],
  ["yangju", "Yangju", "Gyeonggi-do"],
  ["pocheon", "Pocheon", "Gyeonggi-do"],
  ["yeoju", "Yeoju", "Gyeonggi-do"],
  ["chuncheon", "Chuncheon", "Gangwon-do"],
  ["wonju", "Wonju", "Gangwon-do"],
  ["gangneung", "Gangneung", "Gangwon-do"],
  ["donghae", "Donghae", "Gangwon-do"],
  ["taebaek", "Taebaek", "Gangwon-do"],
  ["sokcho", "Sokcho", "Gangwon-do"],
  ["samcheok", "Samcheok", "Gangwon-do"],
  ["cheongju", "Cheongju", "Chungcheongbuk-do"],
  ["chungju", "Chungju", "Chungcheongbuk-do"],
  ["jecheon", "Jecheon", "Chungcheongbuk-do"],
  ["cheonan", "Cheonan", "Chungcheongnam-do"],
  ["gongju", "Gongju", "Chungcheongnam-do"],
  ["boryeong", "Boryeong", "Chungcheongnam-do"],
  ["asan", "Asan", "Chungcheongnam-do"],
  ["seosan", "Seosan", "Chungcheongnam-do"],
  ["nonsan", "Nonsan", "Chungcheongnam-do"],
  ["gyeryong", "Gyeryong", "Chungcheongnam-do"],
  ["dangjin", "Dangjin", "Chungcheongnam-do"],
  ["jeonju", "Jeonju", "Jeollabuk-do"],
  ["gunsan", "Gunsan", "Jeollabuk-do"],
  ["iksan", "Iksan", "Jeollabuk-do"],
  ["jeongeup", "Jeongeup", "Jeollabuk-do"],
  ["namwon", "Namwon", "Jeollabuk-do"],
  ["gimje", "Gimje", "Jeollabuk-do"],
  ["mokpo", "Mokpo", "Jeollanam-do"],
  ["yeosu", "Yeosu", "Jeollanam-do"],
  ["suncheon", "Suncheon", "Jeollanam-do"],
  ["naju", "Naju", "Jeollanam-do"],
  ["gwangyang", "Gwangyang", "Jeollanam-do"],
  ["pohang", "Pohang", "Gyeongsangbuk-do"],
  ["gyeongju", "Gyeongju", "Gyeongsangbuk-do"],
  ["gimcheon", "Gimcheon", "Gyeongsangbuk-do"],
  ["andong", "Andong", "Gyeongsangbuk-do"],
  ["gumi", "Gumi", "Gyeongsangbuk-do"],
  ["yeongju", "Yeongju", "Gyeongsangbuk-do"],
  ["yeongcheon", "Yeongcheon", "Gyeongsangbuk-do"],
  ["sangju", "Sangju", "Gyeongsangbuk-do"],
  ["mungyeong", "Mungyeong", "Gyeongsangbuk-do"],
  ["gyeongsan", "Gyeongsan", "Gyeongsangbuk-do"],
  ["changwon", "Changwon", "Gyeongsangnam-do"],
  ["jinju", "Jinju", "Gyeongsangnam-do"],
  ["tongyeong", "Tongyeong", "Gyeongsangnam-do"],
  ["sacheon", "Sacheon", "Gyeongsangnam-do"],
  ["gimhae", "Gimhae", "Gyeongsangnam-do"],
  ["miryang", "Miryang", "Gyeongsangnam-do"],
  ["geoje", "Geoje", "Gyeongsangnam-do"],
  ["yangsan", "Yangsan", "Gyeongsangnam-do"],
  ["jeju", "Jeju", "Jeju-do"],
  ["seogwipo", "Seogwipo", "Jeju-do"],
] as const;

const accents = [
  "#06b6d4",
  "#f97316",
  "#22c55e",
  "#6366f1",
  "#ef4444",
  "#eab308",
  "#14b8a6",
  "#a855f7",
];

export const cities: City[] = cityRows.map(([slug, name, province], index) => ({
  slug,
  name: { uz: name, ru: name, en: name, ko: name },
  province: { uz: province, ru: province, en: province, ko: province },
  accent: accents[index % accents.length],
}));

export const products: Product[] = [
  {
    id: "local-phone-seoul-1",
    name: {
      uz: "Galaxy S seriyasi, tekshirilgan holat",
      ru: "Galaxy S series, verified condition",
      en: "Galaxy S series, verified condition",
      ko: "Galaxy S series, verified condition",
    },
    citySlug: "seoul",
    category: "phone",
    condition: "used",
    priceKrw: 390000,
    imageUrl:
      "https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?auto=format&fit=crop&w=900&q=80",
    sellerName: "Yongsan Mobile Desk",
    trustLevel: "verified",
    contact: "Kakao: yongsan-demo",
    source: "JUTSU curated",
  },
  {
    id: "local-laptop-seoul-1",
    name: {
      uz: "Ish va o'qish uchun yengil noutbuk",
      ru: "Light laptop for work and study",
      en: "Light laptop for work and study",
      ko: "Light laptop for work and study",
    },
    citySlug: "seoul",
    category: "laptop",
    condition: "refurbished",
    priceKrw: 620000,
    imageUrl:
      "https://images.unsplash.com/photo-1496181133206-80ce9b88a853?auto=format&fit=crop&w=900&q=80",
    sellerName: "Sinchon Tech Corner",
    trustLevel: "community",
    contact: "010-0000-1122",
    source: "JUTSU curated",
  },
  {
    id: "local-rice-busan-1",
    name: {
      uz: "Kichik xona uchun rice cooker",
      ru: "Rice cooker for a small room",
      en: "Rice cooker for a small room",
      ko: "Rice cooker for a small room",
    },
    citySlug: "busan",
    category: "appliance",
    condition: "used",
    priceKrw: 45000,
    imageUrl:
      "https://images.unsplash.com/photo-1556911220-bff31c812dba?auto=format&fit=crop&w=900&q=80",
    sellerName: "Busan Share Market",
    trustLevel: "community",
    contact: "Kakao: busan-share",
    source: "JUTSU curated",
  },
  {
    id: "local-monitor-incheon-1",
    name: {
      uz: "24 dyuym monitor, o'qish va ish uchun",
      ru: "24-inch monitor for study and work",
      en: "24-inch monitor for study and work",
      ko: "24-inch monitor for study and work",
    },
    citySlug: "incheon",
    category: "accessory",
    condition: "used",
    priceKrw: 70000,
    imageUrl:
      "https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?auto=format&fit=crop&w=900&q=80",
    sellerName: "Incheon Desk Setup",
    trustLevel: "verified",
    contact: "010-0000-3344",
    source: "JUTSU curated",
  },
  {
    id: "local-router-daegu-1",
    name: {
      uz: "Wi-Fi router va kabel to'plami",
      ru: "Wi-Fi router and cable kit",
      en: "Wi-Fi router and cable kit",
      ko: "Wi-Fi router and cable kit",
    },
    citySlug: "daegu",
    category: "home",
    condition: "used",
    priceKrw: 28000,
    imageUrl:
      "https://images.unsplash.com/photo-1606904825846-647eb07f5be2?auto=format&fit=crop&w=900&q=80",
    sellerName: "Daegu Room Starter",
    trustLevel: "community",
    contact: "Kakao: daegu-room",
    source: "JUTSU curated",
  },
];

export const restaurants: Restaurant[] = [
  {
    id: "seoul-halal-kitchen",
    name: {
      uz: "Seoul Halal Kitchen",
      ru: "Seoul Halal Kitchen",
      en: "Seoul Halal Kitchen",
      ko: "Seoul Halal Kitchen",
    },
    citySlug: "seoul",
    cuisine: "halal",
    priceBand: "mid",
    halalFriendly: true,
    rating: 4.7,
    imageUrl:
      "https://images.unsplash.com/photo-1601050690597-df0568f70950?auto=format&fit=crop&w=900&q=80",
    address: {
      uz: "Itaewon, Seoul",
      ru: "Itaewon, Seoul",
      en: "Itaewon, Seoul",
      ko: "Itaewon, Seoul",
    },
    menuHighlights: [
      {
        uz: "Halal bulgogi bowl",
        ru: "Halal bulgogi bowl",
        en: "Halal bulgogi bowl",
        ko: "Halal bulgogi bowl",
      },
      {
        uz: "Tovuqli bibimbap",
        ru: "Chicken bibimbap",
        en: "Chicken bibimbap",
        ko: "Chicken bibimbap",
      },
    ],
    contact: "Kakao: halal-seoul-demo",
    source: "JUTSU curated",
  },
  {
    id: "seoul-samarkand-table",
    name: {
      uz: "Samarkand Table",
      ru: "Samarkand Table",
      en: "Samarkand Table",
      ko: "Samarkand Table",
    },
    citySlug: "seoul",
    cuisine: "central-asian",
    priceBand: "budget",
    halalFriendly: true,
    rating: 4.5,
    imageUrl:
      "https://images.unsplash.com/photo-1625944525533-473f1a3d54e7?auto=format&fit=crop&w=900&q=80",
    address: {
      uz: "Dongdaemun, Seoul",
      ru: "Dongdaemun, Seoul",
      en: "Dongdaemun, Seoul",
      ko: "Dongdaemun, Seoul",
    },
    menuHighlights: [
      { uz: "Osh", ru: "Plov", en: "Plov", ko: "Plov" },
      { uz: "Somsa", ru: "Samsa", en: "Samsa", ko: "Samsa" },
    ],
    contact: "010-0000-9921",
    source: "JUTSU curated",
  },
  {
    id: "busan-harbor-noodles",
    name: {
      uz: "Harbor Noodles",
      ru: "Harbor Noodles",
      en: "Harbor Noodles",
      ko: "Harbor Noodles",
    },
    citySlug: "busan",
    cuisine: "korean",
    priceBand: "budget",
    halalFriendly: false,
    rating: 4.4,
    imageUrl:
      "https://images.unsplash.com/photo-1617093727343-374698b1b08d?auto=format&fit=crop&w=900&q=80",
    address: {
      uz: "Haeundae, Busan",
      ru: "Haeundae, Busan",
      en: "Haeundae, Busan",
      ko: "Haeundae, Busan",
    },
    menuHighlights: [
      { uz: "Kalguksu", ru: "Kalguksu", en: "Kalguksu", ko: "Kalguksu" },
      {
        uz: "Kimchi jeon",
        ru: "Kimchi jeon",
        en: "Kimchi jeon",
        ko: "Kimchi jeon",
      },
    ],
    contact: "Kakao: harbor-noodle",
    source: "JUTSU curated",
  },
  {
    id: "incheon-arrival-cafe",
    name: {
      uz: "Arrival Cafe",
      ru: "Arrival Cafe",
      en: "Arrival Cafe",
      ko: "Arrival Cafe",
    },
    citySlug: "incheon",
    cuisine: "cafe",
    priceBand: "mid",
    halalFriendly: false,
    rating: 4.2,
    imageUrl:
      "https://images.unsplash.com/photo-1509042239860-f550ce710b93?auto=format&fit=crop&w=900&q=80",
    address: {
      uz: "Songdo, Incheon",
      ru: "Songdo, Incheon",
      en: "Songdo, Incheon",
      ko: "Songdo, Incheon",
    },
    menuHighlights: [
      { uz: "Americano", ru: "Americano", en: "Americano", ko: "Americano" },
      { uz: "Sandwich", ru: "Sandwich", en: "Sandwich", ko: "Sandwich" },
    ],
    contact: "010-0000-7712",
    source: "JUTSU curated",
  },
  {
    id: "daegu-fast-rice",
    name: {
      uz: "Fast Rice Daegu",
      ru: "Fast Rice Daegu",
      en: "Fast Rice Daegu",
      ko: "Fast Rice Daegu",
    },
    citySlug: "daegu",
    cuisine: "fast",
    priceBand: "budget",
    halalFriendly: false,
    rating: 4.1,
    imageUrl:
      "https://images.unsplash.com/photo-1590301157890-4810ed352733?auto=format&fit=crop&w=900&q=80",
    address: {
      uz: "Jung-gu, Daegu",
      ru: "Jung-gu, Daegu",
      en: "Jung-gu, Daegu",
      ko: "Jung-gu, Daegu",
    },
    menuHighlights: [
      { uz: "Gimbap", ru: "Gimbap", en: "Gimbap", ko: "Gimbap" },
      { uz: "Tteokbokki", ru: "Tteokbokki", en: "Tteokbokki", ko: "Tteokbokki" },
    ],
    contact: "Kakao: daegu-rice",
    source: "JUTSU curated",
  },
];

export const guides: Guide[] = [
  {
    id: "seoul-first-48h",
    citySlug: "seoul",
    category: "setup",
    title: {
      uz: "Seoulda birinchi 48 soat",
      ru: "First 48 hours in Seoul",
      en: "First 48 hours in Seoul",
      ko: "First 48 hours in Seoul",
    },
    summary: {
      uz: "SIM, T-money, arzon ovqat, vaqtinchalik uy va eng kerakli ilovalar.",
      ru: "SIM, T-money, budget food, temporary housing, and key apps.",
      en: "SIM, T-money, budget food, temporary housing, and key apps.",
      ko: "SIM, T-money, budget food, temporary housing, and key apps.",
    },
  },
  {
    id: "busan-starter-kit",
    citySlug: "busan",
    category: "shopping",
    title: {
      uz: "Busanda xonani jihozlash",
      ru: "Setting up a room in Busan",
      en: "Setting up a room in Busan",
      ko: "Setting up a room in Busan",
    },
    summary: {
      uz: "Rice cooker, router, bedding va ishlatilgan monitorni qayerdan olish.",
      ru: "Where to get a rice cooker, router, bedding, and used monitor.",
      en: "Where to get a rice cooker, router, bedding, and used monitor.",
      ko: "Where to get a rice cooker, router, bedding, and used monitor.",
    },
  },
  {
    id: "incheon-arrival",
    citySlug: "incheon",
    category: "transport",
    title: {
      uz: "Aeroportdan shaharga",
      ru: "Airport to city",
      en: "Airport to city",
      ko: "Airport to city",
    },
    summary: {
      uz: "AREX, avtobus, taksi va yuk bilan yurish uchun qisqa checklist.",
      ru: "AREX, bus, taxi, and a short luggage checklist.",
      en: "AREX, bus, taxi, and a short luggage checklist.",
      ko: "AREX, bus, taxi, and a short luggage checklist.",
    },
  },
  {
    id: "daegu-food-map",
    citySlug: "daegu",
    category: "food",
    title: {
      uz: "Daeguda arzon ovqat",
      ru: "Budget food in Daegu",
      en: "Budget food in Daegu",
      ko: "Budget food in Daegu",
    },
    summary: {
      uz: "Talaba va ishchilar uchun tez, arzon va yaqin variantlar.",
      ru: "Fast, nearby options for students and workers.",
      en: "Fast, nearby options for students and workers.",
      ko: "Fast, nearby options for students and workers.",
    },
  },
];
