import { City, Guide, Product, Restaurant } from "./types";

const cityRows = [
  ["seoul", "Seoul", "Seoul Special City"],
  ["busan", "Busan", "Busan Metropolitan City"],
  ["daegu", "Daegu", "Daegu Metropolitan City"],
  ["incheon", "Incheon", "Incheon Metropolitan City"],
  ["gwangju", "Gwangju", "Gwangju Metropolitan City"],
  ["daejeon", "Daejeon", "Daejeon Metropolitan City"],
  ["ulsan", "Ulsan", "Ulsan Metropolitan City"],
  ["sejong", "Sejong", "Sejong Special Self-Governing City"],
  ["suwon", "Suwon", "Gyeonggi-do"],
  ["seongnam", "Seongnam", "Gyeonggi-do"],
  ["uijeongbu", "Uijeongbu", "Gyeonggi-do"],
  ["anyang", "Anyang", "Gyeonggi-do"],
  ["bucheon", "Bucheon", "Gyeonggi-do"],
  ["gwangmyeong", "Gwangmyeong", "Gyeonggi-do"],
  ["pyeongtaek", "Pyeongtaek", "Gyeonggi-do"],
  ["dongducheon", "Dongducheon", "Gyeonggi-do"],
  ["ansan", "Ansan", "Gyeonggi-do"],
  ["goyang", "Goyang", "Gyeonggi-do"],
  ["gwacheon", "Gwacheon", "Gyeonggi-do"],
  ["guri", "Guri", "Gyeonggi-do"],
  ["namyangju", "Namyangju", "Gyeonggi-do"],
  ["osan", "Osan", "Gyeonggi-do"],
  ["siheung", "Siheung", "Gyeonggi-do"],
  ["gunpo", "Gunpo", "Gyeonggi-do"],
  ["uiwang", "Uiwang", "Gyeonggi-do"],
  ["hanam", "Hanam", "Gyeonggi-do"],
  ["yongin", "Yongin", "Gyeonggi-do"],
  ["paju", "Paju", "Gyeonggi-do"],
  ["icheon", "Icheon", "Gyeonggi-do"],
  ["anseong", "Anseong", "Gyeonggi-do"],
  ["gimpo", "Gimpo", "Gyeonggi-do"],
  ["hwaseong", "Hwaseong", "Gyeonggi-do"],
  ["gwangju-gyeonggi", "Gwangju", "Gyeonggi-do"],
  ["yangju", "Yangju", "Gyeonggi-do"],
  ["pocheon", "Pocheon", "Gyeonggi-do"],
  ["yeoju", "Yeoju", "Gyeonggi-do"],
  ["chuncheon", "Chuncheon", "Gangwon-do"],
  ["wonju", "Wonju", "Gangwon-do"],
  ["gangneung", "Gangneung", "Gangwon-do"],
  ["donghae", "Donghae", "Gangwon-do"],
  ["taebaek", "Taebaek", "Gangwon-do"],
  ["sokcho", "Sokcho", "Gangwon-do"],
  ["samcheok", "Samcheok", "Gangwon-do"],
  ["cheongju", "Cheongju", "Chungcheongbuk-do"],
  ["chungju", "Chungju", "Chungcheongbuk-do"],
  ["jecheon", "Jecheon", "Chungcheongbuk-do"],
  ["cheonan", "Cheonan", "Chungcheongnam-do"],
  ["gongju", "Gongju", "Chungcheongnam-do"],
  ["boryeong", "Boryeong", "Chungcheongnam-do"],
  ["asan", "Asan", "Chungcheongnam-do"],
  ["seosan", "Seosan", "Chungcheongnam-do"],
  ["nonsan", "Nonsan", "Chungcheongnam-do"],
  ["gyeryong", "Gyeryong", "Chungcheongnam-do"],
  ["dangjin", "Dangjin", "Chungcheongnam-do"],
  ["jeonju", "Jeonju", "Jeollabuk-do"],
  ["gunsan", "Gunsan", "Jeollabuk-do"],
  ["iksan", "Iksan", "Jeollabuk-do"],
  ["jeongeup", "Jeongeup", "Jeollabuk-do"],
  ["namwon", "Namwon", "Jeollabuk-do"],
  ["gimje", "Gimje", "Jeollabuk-do"],
  ["mokpo", "Mokpo", "Jeollanam-do"],
  ["yeosu", "Yeosu", "Jeollanam-do"],
  ["suncheon", "Suncheon", "Jeollanam-do"],
  ["naju", "Naju", "Jeollanam-do"],
  ["gwangyang", "Gwangyang", "Jeollanam-do"],
  ["pohang", "Pohang", "Gyeongsangbuk-do"],
  ["gyeongju", "Gyeongju", "Gyeongsangbuk-do"],
  ["gimcheon", "Gimcheon", "Gyeongsangbuk-do"],
  ["andong", "Andong", "Gyeongsangbuk-do"],
  ["gumi", "Gumi", "Gyeongsangbuk-do"],
  ["yeongju", "Yeongju", "Gyeongsangbuk-do"],
  ["yeongcheon", "Yeongcheon", "Gyeongsangbuk-do"],
  ["sangju", "Sangju", "Gyeongsangbuk-do"],
  ["mungyeong", "Mungyeong", "Gyeongsangbuk-do"],
  ["gyeongsan", "Gyeongsan", "Gyeongsangbuk-do"],
  ["changwon", "Changwon", "Gyeongsangnam-do"],
  ["jinju", "Jinju", "Gyeongsangnam-do"],
  ["tongyeong", "Tongyeong", "Gyeongsangnam-do"],
  ["sacheon", "Sacheon", "Gyeongsangnam-do"],
  ["gimhae", "Gimhae", "Gyeongsangnam-do"],
  ["miryang", "Miryang", "Gyeongsangnam-do"],
  ["geoje", "Geoje", "Gyeongsangnam-do"],
  ["yangsan", "Yangsan", "Gyeongsangnam-do"],
  ["jeju", "Jeju", "Jeju-do"],
  ["seogwipo", "Seogwipo", "Jeju-do"],
] as const;

const accents = [
  "#06b6d4",
  "#f97316",
  "#22c55e",
  "#6366f1",
  "#ef4444",
  "#eab308",
  "#14b8a6",
  "#a855f7",
];

export const cities: City[] = cityRows.map(([slug, name, province], index) => ({
  slug,
  name: { uz: name, ru: name, en: name, ko: name },
  province: { uz: province, ru: province, en: province, ko: province },
  accent: accents[index % accents.length],
}));

export const products: Product[] = [
  {
    id: "local-phone-seoul-1",
    name: {
      uz: "Samsung Galaxy S23, 256GB, kafolat bilan",
      ru: "Samsung Galaxy S23, 256GB, with warranty",
      en: "Samsung Galaxy S23, 256GB, with warranty",
      ko: "Samsung Galaxy S23, 256GB, with warranty",
    },
    citySlug: "seoul",
    category: "phone",
    condition: "used",
    priceKrw: 390000,
    imageUrl:
      "https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?auto=format&fit=crop&w=900&q=80",
    brand: "Samsung",
    color: "Cream",
    stock: 2,
    tags: ["phone", "galaxy", "256gb", "warranty"],
    optionSummary: {
      uz: "256GB, charger bor, ekran tekshirilgan",
      ru: "256GB, charger included, screen checked",
      en: "256GB, charger included, screen checked",
      ko: "256GB, charger included, screen checked",
    },
    sellerName: "Yongsan Mobile Desk",
    trustLevel: "verified",
    contact: "Kakao: yongsan-demo",
    source: "JUTSU curated",
  },
  {
    id: "local-laptop-seoul-1",
    name: {
      uz: "LG Gram, o'qish va remote ish uchun",
      ru: "LG Gram for study and remote work",
      en: "LG Gram for study and remote work",
      ko: "LG Gram for study and remote work",
    },
    citySlug: "seoul",
    category: "laptop",
    condition: "refurbished",
    priceKrw: 620000,
    imageUrl:
      "https://images.unsplash.com/photo-1496181133206-80ce9b88a853?auto=format&fit=crop&w=900&q=80",
    brand: "LG",
    color: "Silver",
    stock: 1,
    tags: ["laptop", "student", "lightweight"],
    optionSummary: {
      uz: "16GB RAM, 512GB SSD, koreys/ingliz klaviatura",
      ru: "16GB RAM, 512GB SSD, Korean/English keyboard",
      en: "16GB RAM, 512GB SSD, Korean/English keyboard",
      ko: "16GB RAM, 512GB SSD, Korean/English keyboard",
    },
    sellerName: "Sinchon Tech Corner",
    trustLevel: "community",
    contact: "010-0000-1122",
    source: "JUTSU curated",
  },
  {
    id: "local-coat-seoul-1",
    name: {
      uz: "Qish uchun uzun puffer coat",
      ru: "Long winter puffer coat",
      en: "Long winter puffer coat",
      ko: "Long winter puffer coat",
    },
    citySlug: "seoul",
    category: "clothing",
    condition: "new",
    priceKrw: 89000,
    imageUrl:
      "https://images.unsplash.com/photo-1591047139829-d91aecb6caea?auto=format&fit=crop&w=900&q=80",
    brand: "K-Style Basic",
    size: "M / L / XL",
    color: "Black",
    stock: 9,
    tags: ["coat", "winter", "warm", "fashion"],
    optionSummary: {
      uz: "M-L-XL, suv o'tkazmaydigan mato",
      ru: "M-L-XL, water-resistant fabric",
      en: "M-L-XL, water-resistant fabric",
      ko: "M-L-XL, water-resistant fabric",
    },
    sellerName: "Dongdaemun Closet",
    trustLevel: "verified",
    contact: "Kakao: ddm-closet",
    source: "JUTSU curated",
  },
  {
    id: "local-airfryer-seoul-1",
    name: {
      uz: "Mini air fryer, yotoqxona oshxonasi uchun",
      ru: "Mini air fryer for dorm kitchens",
      en: "Mini air fryer for dorm kitchens",
      ko: "Mini air fryer for dorm kitchens",
    },
    citySlug: "seoul",
    category: "appliance",
    condition: "used",
    priceKrw: 52000,
    imageUrl:
      "https://images.unsplash.com/photo-1556911220-bff31c812dba?auto=format&fit=crop&w=900&q=80",
    brand: "Kitchen Mini",
    color: "White",
    stock: 3,
    tags: ["kitchen", "air fryer", "dorm"],
    optionSummary: {
      uz: "2L, tozalangan, 220V",
      ru: "2L, cleaned, 220V",
      en: "2L, cleaned, 220V",
      ko: "2L, cleaned, 220V",
    },
    sellerName: "Hongdae Room Market",
    trustLevel: "community",
    contact: "010-0000-2211",
    source: "JUTSU curated",
  },
  {
    id: "local-desk-seoul-1",
    name: {
      uz: "Stol va ergonomik stul starter bundle",
      ru: "Desk and ergonomic chair starter bundle",
      en: "Desk and ergonomic chair starter bundle",
      ko: "Desk and ergonomic chair starter bundle",
    },
    citySlug: "seoul",
    category: "furniture",
    condition: "used",
    priceKrw: 94000,
    imageUrl:
      "https://images.unsplash.com/photo-1555041469-a586c61ea9bc?auto=format&fit=crop&w=900&q=80",
    brand: "RoomFit",
    color: "Oak / Black",
    stock: 2,
    tags: ["room", "desk", "chair", "work"],
    optionSummary: {
      uz: "Stol 120cm, stul balandligi sozlanadi",
      ru: "120cm desk, adjustable chair",
      en: "120cm desk, adjustable chair",
      ko: "120cm desk, adjustable chair",
    },
    sellerName: "Seoul Room Starter",
    trustLevel: "verified",
    contact: "Kakao: roomfit-seoul",
    source: "JUTSU curated",
  },
  {
    id: "local-rice-busan-1",
    name: {
      uz: "Kichik xona uchun rice cooker",
      ru: "Rice cooker for a small room",
      en: "Rice cooker for a small room",
      ko: "Rice cooker for a small room",
    },
    citySlug: "busan",
    category: "appliance",
    condition: "used",
    priceKrw: 45000,
    imageUrl:
      "https://images.unsplash.com/photo-1556911220-bff31c812dba?auto=format&fit=crop&w=900&q=80",
    brand: "Cuckoo",
    color: "White",
    stock: 4,
    tags: ["kitchen", "rice cooker", "starter"],
    optionSummary: {
      uz: "3-4 porsiya, kabel va o'lchov kosasi bor",
      ru: "3-4 servings, cable and measuring cup included",
      en: "3-4 servings, cable and measuring cup included",
      ko: "3-4 servings, cable and measuring cup included",
    },
    sellerName: "Busan Share Market",
    trustLevel: "community",
    contact: "Kakao: busan-share",
    source: "JUTSU curated",
  },
  {
    id: "local-raincoat-busan-1",
    name: {
      uz: "Busan yomg'iri uchun light jacket",
      ru: "Light jacket for Busan rain",
      en: "Light jacket for Busan rain",
      ko: "Light jacket for Busan rain",
    },
    citySlug: "busan",
    category: "clothing",
    condition: "new",
    priceKrw: 49000,
    imageUrl:
      "https://images.unsplash.com/photo-1551488831-00ddcb6c6bd3?auto=format&fit=crop&w=900&q=80",
    brand: "Harbor Wear",
    size: "S / M / L",
    color: "Navy",
    stock: 12,
    tags: ["jacket", "rain", "busan"],
    optionSummary: {
      uz: "Yengil, kapyushonli, tez quriydi",
      ru: "Lightweight, hooded, quick dry",
      en: "Lightweight, hooded, quick dry",
      ko: "Lightweight, hooded, quick dry",
    },
    sellerName: "Haeundae Closet",
    trustLevel: "verified",
    contact: "010-0000-7721",
    source: "JUTSU curated",
  },
  {
    id: "local-sneakers-busan-1",
    name: {
      uz: "Daily sneakers, ko'p yurishga qulay",
      ru: "Daily sneakers for long walks",
      en: "Daily sneakers for long walks",
      ko: "Daily sneakers for long walks",
    },
    citySlug: "busan",
    category: "shoes",
    condition: "new",
    priceKrw: 69000,
    imageUrl:
      "https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=900&q=80",
    brand: "Street Run",
    size: "250-285mm",
    color: "Red / White",
    stock: 18,
    tags: ["sneakers", "walking", "shoes"],
    optionSummary: {
      uz: "250-285mm, yengil taglik",
      ru: "250-285mm, lightweight sole",
      en: "250-285mm, lightweight sole",
      ko: "250-285mm, lightweight sole",
    },
    sellerName: "Busan Street Gear",
    trustLevel: "community",
    contact: "Kakao: street-busan",
    source: "JUTSU curated",
  },
  {
    id: "local-cookware-busan-1",
    name: {
      uz: "Oshxona pot + pan to'plami",
      ru: "Kitchen pot + pan set",
      en: "Kitchen pot + pan set",
      ko: "Kitchen pot + pan set",
    },
    citySlug: "busan",
    category: "appliance",
    condition: "new",
    priceKrw: 58000,
    imageUrl:
      "https://images.unsplash.com/photo-1556911220-bff31c812dba?auto=format&fit=crop&w=900&q=80",
    brand: "CookMate",
    color: "Steel",
    stock: 7,
    tags: ["kitchen", "pan", "pot"],
    optionSummary: {
      uz: "2 ta pot, 1 ta pan, induction mos",
      ru: "2 pots, 1 pan, induction-ready",
      en: "2 pots, 1 pan, induction-ready",
      ko: "2 pots, 1 pan, induction-ready",
    },
    sellerName: "Busan Kitchen Kit",
    trustLevel: "verified",
    contact: "010-0000-4491",
    source: "JUTSU curated",
  },
  {
    id: "local-monitor-incheon-1",
    name: {
      uz: "24 dyuym monitor, o'qish va ish uchun",
      ru: "24-inch monitor for study and work",
      en: "24-inch monitor for study and work",
      ko: "24-inch monitor for study and work",
    },
    citySlug: "incheon",
    category: "accessory",
    condition: "used",
    priceKrw: 70000,
    imageUrl:
      "https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?auto=format&fit=crop&w=900&q=80",
    brand: "LG",
    color: "Black",
    stock: 5,
    tags: ["monitor", "desk", "study"],
    optionSummary: {
      uz: "HDMI kabel bor, 24 dyuym, no dead pixel",
      ru: "HDMI cable included, 24-inch, no dead pixels",
      en: "HDMI cable included, 24-inch, no dead pixels",
      ko: "HDMI cable included, 24-inch, no dead pixels",
    },
    sellerName: "Incheon Desk Setup",
    trustLevel: "verified",
    contact: "010-0000-3344",
    source: "JUTSU curated",
  },
  {
    id: "local-coat-incheon-1",
    name: {
      uz: "Incheon qishi uchun warm coat",
      ru: "Warm coat for Incheon winter",
      en: "Warm coat for Incheon winter",
      ko: "Warm coat for Incheon winter",
    },
    citySlug: "incheon",
    category: "clothing",
    condition: "new",
    priceKrw: 79000,
    imageUrl:
      "https://images.unsplash.com/photo-1591047139829-d91aecb6caea?auto=format&fit=crop&w=900&q=80",
    brand: "Songdo Wear",
    size: "M / L / XL",
    color: "Black",
    stock: 10,
    tags: ["coat", "winter", "clothing"],
    optionSummary: {
      uz: "Qalin, shamol o'tkazmaydi, M-L-XL",
      ru: "Warm, wind-resistant, M-L-XL",
      en: "Warm, wind-resistant, M-L-XL",
      ko: "Warm, wind-resistant, M-L-XL",
    },
    sellerName: "Songdo Closet",
    trustLevel: "verified",
    contact: "Kakao: songdo-closet",
    source: "JUTSU curated",
  },
  {
    id: "local-hoodie-incheon-1",
    name: {
      uz: "Oversize hoodie, kundalik kiyim",
      ru: "Oversize hoodie for daily wear",
      en: "Oversize hoodie for daily wear",
      ko: "Oversize hoodie for daily wear",
    },
    citySlug: "incheon",
    category: "clothing",
    condition: "new",
    priceKrw: 39000,
    imageUrl:
      "https://images.unsplash.com/photo-1603252109303-2751441dd157?auto=format&fit=crop&w=900&q=80",
    brand: "JUTSU Basic",
    size: "Free / L",
    color: "Grey",
    stock: 16,
    tags: ["hoodie", "basic", "student"],
    optionSummary: {
      uz: "Free size, paxta aralash mato",
      ru: "Free size, cotton blend",
      en: "Free size, cotton blend",
      ko: "Free size, cotton blend",
    },
    sellerName: "Bupyeong Fashion Desk",
    trustLevel: "community",
    contact: "010-0000-1207",
    source: "JUTSU curated",
  },
  {
    id: "local-sneakers-incheon-1",
    name: {
      uz: "Oq sneakers, kampus va ish uchun",
      ru: "White sneakers for campus and work",
      en: "White sneakers for campus and work",
      ko: "White sneakers for campus and work",
    },
    citySlug: "incheon",
    category: "shoes",
    condition: "new",
    priceKrw: 68000,
    imageUrl:
      "https://images.unsplash.com/photo-1560769629-975ec94e6a86?auto=format&fit=crop&w=900&q=80",
    brand: "Daily Step",
    size: "240-285mm",
    color: "White",
    stock: 22,
    tags: ["shoes", "sneakers", "white"],
    optionSummary: {
      uz: "240-285mm, rezina taglik, daily fit",
      ru: "240-285mm, rubber sole, daily fit",
      en: "240-285mm, rubber sole, daily fit",
      ko: "240-285mm, rubber sole, daily fit",
    },
    sellerName: "Incheon Street Shop",
    trustLevel: "verified",
    contact: "Kakao: icn-sneakers",
    source: "JUTSU curated",
  },
  {
    id: "local-kitchen-incheon-1",
    name: {
      uz: "Induction va pan mini oshxona seti",
      ru: "Induction and pan mini kitchen set",
      en: "Induction and pan mini kitchen set",
      ko: "Induction and pan mini kitchen set",
    },
    citySlug: "incheon",
    category: "appliance",
    condition: "new",
    priceKrw: 99000,
    imageUrl:
      "https://images.unsplash.com/photo-1556911220-bff31c812dba?auto=format&fit=crop&w=900&q=80",
    brand: "CookMate",
    color: "Black",
    stock: 6,
    tags: ["kitchen", "induction", "pan", "starter"],
    optionSummary: {
      uz: "1 burner induction, non-stick pan, 220V",
      ru: "1-burner induction, non-stick pan, 220V",
      en: "1-burner induction, non-stick pan, 220V",
      ko: "1-burner induction, non-stick pan, 220V",
    },
    sellerName: "Incheon Kitchen Kit",
    trustLevel: "verified",
    contact: "010-0000-5560",
    source: "JUTSU curated",
  },
  {
    id: "local-fridge-incheon-1",
    name: {
      uz: "Mini fridge, yotoqxona uchun",
      ru: "Mini fridge for a dorm room",
      en: "Mini fridge for a dorm room",
      ko: "Mini fridge for a dorm room",
    },
    citySlug: "incheon",
    category: "appliance",
    condition: "used",
    priceKrw: 115000,
    imageUrl:
      "https://images.unsplash.com/photo-1580587771525-78b9dba3b914?auto=format&fit=crop&w=900&q=80",
    brand: "Daewoo",
    color: "White",
    stock: 2,
    tags: ["kitchen", "fridge", "room"],
    optionSummary: {
      uz: "90L, ichki tozalangan, pickup yoki delivery",
      ru: "90L, cleaned inside, pickup or delivery",
      en: "90L, cleaned inside, pickup or delivery",
      ko: "90L, cleaned inside, pickup or delivery",
    },
    sellerName: "Yeonsu Home Share",
    trustLevel: "community",
    contact: "Kakao: yeonsu-home",
    source: "JUTSU curated",
  },
  {
    id: "local-phone-incheon-1",
    name: {
      uz: "Galaxy A seriyasi, arzon starter phone",
      ru: "Galaxy A series budget starter phone",
      en: "Galaxy A series budget starter phone",
      ko: "Galaxy A series budget starter phone",
    },
    citySlug: "incheon",
    category: "phone",
    condition: "refurbished",
    priceKrw: 210000,
    imageUrl:
      "https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?auto=format&fit=crop&w=900&q=80",
    brand: "Samsung",
    color: "Graphite",
    stock: 4,
    tags: ["phone", "galaxy", "budget"],
    optionSummary: {
      uz: "128GB, SIM-free, battery 88%+",
      ru: "128GB, SIM-free, battery 88%+",
      en: "128GB, SIM-free, battery 88%+",
      ko: "128GB, SIM-free, battery 88%+",
    },
    sellerName: "Bupyeong Mobile",
    trustLevel: "verified",
    contact: "010-0000-9173",
    source: "JUTSU curated",
  },
  {
    id: "local-laptop-incheon-1",
    name: {
      uz: "ThinkPad, kodlash va ofis uchun",
      ru: "ThinkPad for coding and office work",
      en: "ThinkPad for coding and office work",
      ko: "ThinkPad for coding and office work",
    },
    citySlug: "incheon",
    category: "laptop",
    condition: "used",
    priceKrw: 540000,
    imageUrl:
      "https://images.unsplash.com/photo-1496181133206-80ce9b88a853?auto=format&fit=crop&w=900&q=80",
    brand: "Lenovo",
    color: "Black",
    stock: 2,
    tags: ["laptop", "coding", "office"],
    optionSummary: {
      uz: "16GB RAM, 512GB SSD, Type-C charger",
      ru: "16GB RAM, 512GB SSD, Type-C charger",
      en: "16GB RAM, 512GB SSD, Type-C charger",
      ko: "16GB RAM, 512GB SSD, Type-C charger",
    },
    sellerName: "Incheon Tech Reuse",
    trustLevel: "verified",
    contact: "Kakao: icn-tech",
    source: "JUTSU curated",
  },
  {
    id: "local-bedding-incheon-1",
    name: {
      uz: "Bedding starter pack, yostiq va ko'rpa",
      ru: "Bedding starter pack with pillow and blanket",
      en: "Bedding starter pack with pillow and blanket",
      ko: "Bedding starter pack with pillow and blanket",
    },
    citySlug: "incheon",
    category: "home",
    condition: "new",
    priceKrw: 59000,
    imageUrl:
      "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=900&q=80",
    brand: "RoomFit",
    size: "Single",
    color: "Ivory",
    stock: 11,
    tags: ["bedding", "room", "starter"],
    optionSummary: {
      uz: "Single size, pillow + blanket + cover",
      ru: "Single size, pillow + blanket + cover",
      en: "Single size, pillow + blanket + cover",
      ko: "Single size, pillow + blanket + cover",
    },
    sellerName: "Songdo Room Pack",
    trustLevel: "verified",
    contact: "010-0000-3388",
    source: "JUTSU curated",
  },
  {
    id: "local-chair-incheon-1",
    name: {
      uz: "Ish uchun desk chair",
      ru: "Desk chair for work",
      en: "Desk chair for work",
      ko: "Desk chair for work",
    },
    citySlug: "incheon",
    category: "furniture",
    condition: "used",
    priceKrw: 45000,
    imageUrl:
      "https://images.unsplash.com/photo-1555041469-a586c61ea9bc?auto=format&fit=crop&w=900&q=80",
    brand: "RoomFit",
    color: "Black",
    stock: 3,
    tags: ["chair", "desk", "room"],
    optionSummary: {
      uz: "Balandligi sozlanadi, Songdo pickup",
      ru: "Adjustable height, Songdo pickup",
      en: "Adjustable height, Songdo pickup",
      ko: "Adjustable height, Songdo pickup",
    },
    sellerName: "Incheon Desk Setup",
    trustLevel: "community",
    contact: "010-0000-3344",
    source: "JUTSU curated",
  },
  {
    id: "local-backpack-incheon-1",
    name: {
      uz: "Laptop backpack, suv o'tkazmaydigan",
      ru: "Water-resistant laptop backpack",
      en: "Water-resistant laptop backpack",
      ko: "Water-resistant laptop backpack",
    },
    citySlug: "incheon",
    category: "accessory",
    condition: "new",
    priceKrw: 32000,
    imageUrl:
      "https://images.unsplash.com/photo-1523381210434-271e8be1f52b?auto=format&fit=crop&w=900&q=80",
    brand: "Daily Pack",
    size: "15-inch laptop",
    color: "Charcoal",
    stock: 13,
    tags: ["bag", "laptop", "student"],
    optionSummary: {
      uz: "15 dyuym laptop sig'adi, USB pocket",
      ru: "Fits 15-inch laptop, USB pocket",
      en: "Fits 15-inch laptop, USB pocket",
      ko: "Fits 15-inch laptop, USB pocket",
    },
    sellerName: "Bupyeong Fashion Desk",
    trustLevel: "verified",
    contact: "Kakao: bupyeong-pack",
    source: "JUTSU curated",
  },
  {
    id: "local-rice-incheon-1",
    name: {
      uz: "Rice cooker, yakka yashash uchun",
      ru: "Rice cooker for solo living",
      en: "Rice cooker for solo living",
      ko: "Rice cooker for solo living",
    },
    citySlug: "incheon",
    category: "appliance",
    condition: "used",
    priceKrw: 48000,
    imageUrl:
      "https://images.unsplash.com/photo-1556911220-bff31c812dba?auto=format&fit=crop&w=900&q=80",
    brand: "Cuckoo",
    color: "White",
    stock: 4,
    tags: ["kitchen", "rice cooker", "solo"],
    optionSummary: {
      uz: "2-3 porsiya, ichki qismi yaxshi holatda",
      ru: "2-3 servings, inner pot in good condition",
      en: "2-3 servings, inner pot in good condition",
      ko: "2-3 servings, inner pot in good condition",
    },
    sellerName: "Incheon Kitchen Kit",
    trustLevel: "community",
    contact: "010-0000-5560",
    source: "JUTSU curated",
  },
  {
    id: "local-router-daegu-1",
    name: {
      uz: "Wi-Fi router va kabel to'plami",
      ru: "Wi-Fi router and cable kit",
      en: "Wi-Fi router and cable kit",
      ko: "Wi-Fi router and cable kit",
    },
    citySlug: "daegu",
    category: "home",
    condition: "used",
    priceKrw: 28000,
    imageUrl:
      "https://images.unsplash.com/photo-1606904825846-647eb07f5be2?auto=format&fit=crop&w=900&q=80",
    brand: "ipTIME",
    color: "White",
    stock: 7,
    tags: ["wifi", "router", "internet"],
    optionSummary: {
      uz: "Router + LAN kabel, 5GHz qo'llab-quvvatlaydi",
      ru: "Router + LAN cable, supports 5GHz",
      en: "Router + LAN cable, supports 5GHz",
      ko: "Router + LAN cable, supports 5GHz",
    },
    sellerName: "Daegu Room Starter",
    trustLevel: "community",
    contact: "Kakao: daegu-room",
    source: "JUTSU curated",
  },
  {
    id: "local-hoodie-daegu-1",
    name: {
      uz: "Basic hoodie va jogger set",
      ru: "Basic hoodie and jogger set",
      en: "Basic hoodie and jogger set",
      ko: "Basic hoodie and jogger set",
    },
    citySlug: "daegu",
    category: "clothing",
    condition: "new",
    priceKrw: 62000,
    imageUrl:
      "https://images.unsplash.com/photo-1603252109303-2751441dd157?auto=format&fit=crop&w=900&q=80",
    brand: "Daegu Basic",
    size: "M / L",
    color: "Melange Grey",
    stock: 8,
    tags: ["hoodie", "jogger", "set"],
    optionSummary: {
      uz: "Hoodie + jogger, M-L",
      ru: "Hoodie + jogger, M-L",
      en: "Hoodie + jogger, M-L",
      ko: "Hoodie + jogger, M-L",
    },
    sellerName: "Daegu Fashion Room",
    trustLevel: "verified",
    contact: "010-0000-7044",
    source: "JUTSU curated",
  },
  {
    id: "local-kettle-daegu-1",
    name: {
      uz: "Elektr choynak, tez qaynatadi",
      ru: "Fast electric kettle",
      en: "Fast electric kettle",
      ko: "Fast electric kettle",
    },
    citySlug: "daegu",
    category: "appliance",
    condition: "new",
    priceKrw: 24000,
    imageUrl:
      "https://images.unsplash.com/photo-1556911220-bff31c812dba?auto=format&fit=crop&w=900&q=80",
    brand: "Kitchen Mini",
    color: "Steel",
    stock: 10,
    tags: ["kitchen", "kettle", "tea"],
    optionSummary: {
      uz: "1.5L, avtomatik o'chadi",
      ru: "1.5L, auto shut-off",
      en: "1.5L, auto shut-off",
      ko: "1.5L, auto shut-off",
    },
    sellerName: "Daegu Room Starter",
    trustLevel: "verified",
    contact: "Kakao: daegu-room",
    source: "JUTSU curated",
  },
  {
    id: "local-monitor-suwon-1",
    name: {
      uz: "27 dyuym monitor, dual setup uchun",
      ru: "27-inch monitor for dual setup",
      en: "27-inch monitor for dual setup",
      ko: "27-inch monitor for dual setup",
    },
    citySlug: "suwon",
    category: "accessory",
    condition: "used",
    priceKrw: 120000,
    imageUrl:
      "https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?auto=format&fit=crop&w=900&q=80",
    brand: "Samsung",
    color: "Black",
    stock: 2,
    tags: ["monitor", "office", "gaming"],
    optionSummary: {
      uz: "27 dyuym, HDMI/DP, stend bor",
      ru: "27-inch, HDMI/DP, stand included",
      en: "27-inch, HDMI/DP, stand included",
      ko: "27-inch, HDMI/DP, stand included",
    },
    sellerName: "Suwon Tech Lane",
    trustLevel: "community",
    contact: "010-0000-8701",
    source: "JUTSU curated",
  },
  {
    id: "local-coat-suwon-1",
    name: {
      uz: "Daily trench coat",
      ru: "Daily trench coat",
      en: "Daily trench coat",
      ko: "Daily trench coat",
    },
    citySlug: "suwon",
    category: "clothing",
    condition: "new",
    priceKrw: 73000,
    imageUrl:
      "https://images.unsplash.com/photo-1503342217505-b0a15ec3261c?auto=format&fit=crop&w=900&q=80",
    brand: "Suwon Fit",
    size: "S / M / L",
    color: "Beige",
    stock: 7,
    tags: ["coat", "fashion", "daily"],
    optionSummary: {
      uz: "S-M-L, office va daily look",
      ru: "S-M-L, office and daily look",
      en: "S-M-L, office and daily look",
      ko: "S-M-L, office and daily look",
    },
    sellerName: "Suwon Fashion Desk",
    trustLevel: "verified",
    contact: "Kakao: suwon-fit",
    source: "JUTSU curated",
  },
  {
    id: "local-laptop-daejeon-1",
    name: {
      uz: "Coding laptop, student discount",
      ru: "Coding laptop, student discount",
      en: "Coding laptop, student discount",
      ko: "Coding laptop, student discount",
    },
    citySlug: "daejeon",
    category: "laptop",
    condition: "refurbished",
    priceKrw: 590000,
    imageUrl:
      "https://images.unsplash.com/photo-1496181133206-80ce9b88a853?auto=format&fit=crop&w=900&q=80",
    brand: "Dell",
    color: "Grey",
    stock: 2,
    tags: ["laptop", "coding", "student"],
    optionSummary: {
      uz: "i7, 16GB RAM, 512GB SSD",
      ru: "i7, 16GB RAM, 512GB SSD",
      en: "i7, 16GB RAM, 512GB SSD",
      ko: "i7, 16GB RAM, 512GB SSD",
    },
    sellerName: "Daejeon Campus Tech",
    trustLevel: "verified",
    contact: "010-0000-6811",
    source: "JUTSU curated",
  },
  {
    id: "local-shoes-daejeon-1",
    name: {
      uz: "Qora sneakers, ish va o'qish uchun",
      ru: "Black sneakers for work and study",
      en: "Black sneakers for work and study",
      ko: "Black sneakers for work and study",
    },
    citySlug: "daejeon",
    category: "shoes",
    condition: "new",
    priceKrw: 64000,
    imageUrl:
      "https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=900&q=80",
    brand: "Campus Step",
    size: "250-280mm",
    color: "Black",
    stock: 9,
    tags: ["shoes", "sneakers", "campus"],
    optionSummary: {
      uz: "250-280mm, slip-resistant sole",
      ru: "250-280mm, slip-resistant sole",
      en: "250-280mm, slip-resistant sole",
      ko: "250-280mm, slip-resistant sole",
    },
    sellerName: "Daejeon Street Gear",
    trustLevel: "community",
    contact: "Kakao: daejeon-step",
    source: "JUTSU curated",
  },
  {
    id: "local-phone-gwangju-1",
    name: {
      uz: "iPhone starter, eSIM tayyor",
      ru: "iPhone starter, eSIM-ready",
      en: "iPhone starter, eSIM-ready",
      ko: "iPhone starter, eSIM-ready",
    },
    citySlug: "gwangju",
    category: "phone",
    condition: "used",
    priceKrw: 430000,
    imageUrl:
      "https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?auto=format&fit=crop&w=900&q=80",
    brand: "Apple",
    color: "Midnight",
    stock: 2,
    tags: ["iphone", "esim", "phone"],
    optionSummary: {
      uz: "128GB, eSIM, battery 86%+",
      ru: "128GB, eSIM, battery 86%+",
      en: "128GB, eSIM, battery 86%+",
      ko: "128GB, eSIM, battery 86%+",
    },
    sellerName: "Gwangju Mobile Desk",
    trustLevel: "verified",
    contact: "010-0000-4903",
    source: "JUTSU curated",
  },
  {
    id: "local-pot-gwangju-1",
    name: {
      uz: "Soup pot, osh va ramen uchun",
      ru: "Soup pot for plov and ramen",
      en: "Soup pot for plov and ramen",
      ko: "Soup pot for plov and ramen",
    },
    citySlug: "gwangju",
    category: "appliance",
    condition: "new",
    priceKrw: 29000,
    imageUrl:
      "https://images.unsplash.com/photo-1556911220-bff31c812dba?auto=format&fit=crop&w=900&q=80",
    brand: "CookMate",
    color: "Steel",
    stock: 14,
    tags: ["kitchen", "pot", "ramen"],
    optionSummary: {
      uz: "22cm, induction va gas uchun mos",
      ru: "22cm, induction and gas compatible",
      en: "22cm, induction and gas compatible",
      ko: "22cm, induction and gas compatible",
    },
    sellerName: "Gwangju Kitchen Kit",
    trustLevel: "verified",
    contact: "Kakao: gwangju-cook",
    source: "JUTSU curated",
  },
  {
    id: "local-windbreaker-jeju-1",
    name: {
      uz: "Jeju shamoli uchun windbreaker",
      ru: "Windbreaker for Jeju weather",
      en: "Windbreaker for Jeju weather",
      ko: "Windbreaker for Jeju weather",
    },
    citySlug: "jeju",
    category: "clothing",
    condition: "new",
    priceKrw: 57000,
    imageUrl:
      "https://images.unsplash.com/photo-1551488831-00ddcb6c6bd3?auto=format&fit=crop&w=900&q=80",
    brand: "Island Wear",
    size: "S / M / L / XL",
    color: "Olive",
    stock: 15,
    tags: ["jacket", "windbreaker", "jeju"],
    optionSummary: {
      uz: "Yengil, kapyushonli, shamolga chidamli",
      ru: "Light, hooded, wind-resistant",
      en: "Light, hooded, wind-resistant",
      ko: "Light, hooded, wind-resistant",
    },
    sellerName: "Jeju Island Gear",
    trustLevel: "verified",
    contact: "010-0000-3322",
    source: "JUTSU curated",
  },
  {
    id: "local-bedroom-jeju-1",
    name: {
      uz: "Small room organizer va hanger set",
      ru: "Small room organizer and hanger set",
      en: "Small room organizer and hanger set",
      ko: "Small room organizer and hanger set",
    },
    citySlug: "jeju",
    category: "home",
    condition: "new",
    priceKrw: 36000,
    imageUrl:
      "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=900&q=80",
    brand: "RoomFit",
    color: "White",
    stock: 8,
    tags: ["room", "organizer", "hanger"],
    optionSummary: {
      uz: "10 hanger, shelf organizer, drawer box",
      ru: "10 hangers, shelf organizer, drawer box",
      en: "10 hangers, shelf organizer, drawer box",
      ko: "10 hangers, shelf organizer, drawer box",
    },
    sellerName: "Jeju Room Starter",
    trustLevel: "community",
    contact: "Kakao: jeju-room",
    source: "JUTSU curated",
  },
];

export const restaurants: Restaurant[] = [
  {
    id: "seoul-halal-kitchen",
    name: {
      uz: "Seoul Halal Kitchen",
      ru: "Seoul Halal Kitchen",
      en: "Seoul Halal Kitchen",
      ko: "Seoul Halal Kitchen",
    },
    citySlug: "seoul",
    cuisine: "halal",
    priceBand: "mid",
    halalFriendly: true,
    rating: 4.7,
    imageUrl:
      "https://images.unsplash.com/photo-1601050690597-df0568f70950?auto=format&fit=crop&w=900&q=80",
    address: {
      uz: "Itaewon, Seoul",
      ru: "Itaewon, Seoul",
      en: "Itaewon, Seoul",
      ko: "Itaewon, Seoul",
    },
    menuHighlights: [
      {
        uz: "Halal bulgogi bowl",
        ru: "Halal bulgogi bowl",
        en: "Halal bulgogi bowl",
        ko: "Halal bulgogi bowl",
      },
      {
        uz: "Tovuqli bibimbap",
        ru: "Chicken bibimbap",
        en: "Chicken bibimbap",
        ko: "Chicken bibimbap",
      },
    ],
    contact: "Kakao: halal-seoul-demo",
    source: "JUTSU curated",
  },
  {
    id: "seoul-samarkand-table",
    name: {
      uz: "Samarkand Table",
      ru: "Samarkand Table",
      en: "Samarkand Table",
      ko: "Samarkand Table",
    },
    citySlug: "seoul",
    cuisine: "central-asian",
    priceBand: "budget",
    halalFriendly: true,
    rating: 4.5,
    imageUrl:
      "https://images.unsplash.com/photo-1625944525533-473f1a3d54e7?auto=format&fit=crop&w=900&q=80",
    address: {
      uz: "Dongdaemun, Seoul",
      ru: "Dongdaemun, Seoul",
      en: "Dongdaemun, Seoul",
      ko: "Dongdaemun, Seoul",
    },
    menuHighlights: [
      { uz: "Osh", ru: "Plov", en: "Plov", ko: "Plov" },
      { uz: "Somsa", ru: "Samsa", en: "Samsa", ko: "Samsa" },
    ],
    contact: "010-0000-9921",
    source: "JUTSU curated",
  },
  {
    id: "busan-harbor-noodles",
    name: {
      uz: "Harbor Noodles",
      ru: "Harbor Noodles",
      en: "Harbor Noodles",
      ko: "Harbor Noodles",
    },
    citySlug: "busan",
    cuisine: "korean",
    priceBand: "budget",
    halalFriendly: false,
    rating: 4.4,
    imageUrl:
      "https://images.unsplash.com/photo-1617093727343-374698b1b08d?auto=format&fit=crop&w=900&q=80",
    address: {
      uz: "Haeundae, Busan",
      ru: "Haeundae, Busan",
      en: "Haeundae, Busan",
      ko: "Haeundae, Busan",
    },
    menuHighlights: [
      { uz: "Kalguksu", ru: "Kalguksu", en: "Kalguksu", ko: "Kalguksu" },
      {
        uz: "Kimchi jeon",
        ru: "Kimchi jeon",
        en: "Kimchi jeon",
        ko: "Kimchi jeon",
      },
    ],
    contact: "Kakao: harbor-noodle",
    source: "JUTSU curated",
  },
  {
    id: "incheon-arrival-cafe",
    name: {
      uz: "Arrival Cafe",
      ru: "Arrival Cafe",
      en: "Arrival Cafe",
      ko: "Arrival Cafe",
    },
    citySlug: "incheon",
    cuisine: "cafe",
    priceBand: "mid",
    halalFriendly: false,
    rating: 4.2,
    imageUrl:
      "https://images.unsplash.com/photo-1509042239860-f550ce710b93?auto=format&fit=crop&w=900&q=80",
    address: {
      uz: "Songdo, Incheon",
      ru: "Songdo, Incheon",
      en: "Songdo, Incheon",
      ko: "Songdo, Incheon",
    },
    menuHighlights: [
      { uz: "Americano", ru: "Americano", en: "Americano", ko: "Americano" },
      { uz: "Sandwich", ru: "Sandwich", en: "Sandwich", ko: "Sandwich" },
    ],
    contact: "010-0000-7712",
    source: "JUTSU curated",
  },
  {
    id: "daegu-fast-rice",
    name: {
      uz: "Fast Rice Daegu",
      ru: "Fast Rice Daegu",
      en: "Fast Rice Daegu",
      ko: "Fast Rice Daegu",
    },
    citySlug: "daegu",
    cuisine: "fast",
    priceBand: "budget",
    halalFriendly: false,
    rating: 4.1,
    imageUrl:
      "https://images.unsplash.com/photo-1590301157890-4810ed352733?auto=format&fit=crop&w=900&q=80",
    address: {
      uz: "Jung-gu, Daegu",
      ru: "Jung-gu, Daegu",
      en: "Jung-gu, Daegu",
      ko: "Jung-gu, Daegu",
    },
    menuHighlights: [
      { uz: "Gimbap", ru: "Gimbap", en: "Gimbap", ko: "Gimbap" },
      { uz: "Tteokbokki", ru: "Tteokbokki", en: "Tteokbokki", ko: "Tteokbokki" },
    ],
    contact: "Kakao: daegu-rice",
    source: "JUTSU curated",
  },
];

export const guides: Guide[] = [
  {
    id: "seoul-first-48h",
    citySlug: "seoul",
    category: "setup",
    title: {
      uz: "Seoulda birinchi 48 soat",
      ru: "First 48 hours in Seoul",
      en: "First 48 hours in Seoul",
      ko: "First 48 hours in Seoul",
    },
    summary: {
      uz: "SIM, T-money, arzon ovqat, vaqtinchalik uy va eng kerakli ilovalar.",
      ru: "SIM, T-money, budget food, temporary housing, and key apps.",
      en: "SIM, T-money, budget food, temporary housing, and key apps.",
      ko: "SIM, T-money, budget food, temporary housing, and key apps.",
    },
  },
  {
    id: "busan-starter-kit",
    citySlug: "busan",
    category: "shopping",
    title: {
      uz: "Busanda xonani jihozlash",
      ru: "Setting up a room in Busan",
      en: "Setting up a room in Busan",
      ko: "Setting up a room in Busan",
    },
    summary: {
      uz: "Rice cooker, router, bedding va ishlatilgan monitorni qayerdan olish.",
      ru: "Where to get a rice cooker, router, bedding, and used monitor.",
      en: "Where to get a rice cooker, router, bedding, and used monitor.",
      ko: "Where to get a rice cooker, router, bedding, and used monitor.",
    },
  },
  {
    id: "incheon-arrival",
    citySlug: "incheon",
    category: "clothing",
    title: {
      uz: "Incheonda birinchi kiyim-kechak xaridi",
      ru: "First clothing shopping in Incheon",
      en: "First clothing shopping in Incheon",
      ko: "First clothing shopping in Incheon",
    },
    summary: {
      uz: "Qishki coat, hoodie, sneaker, ish kiyimi va o'lcham tanlash uchun qisqa checklist.",
      ru: "A short checklist for winter coats, hoodies, sneakers, workwear, and sizing.",
      en: "A short checklist for winter coats, hoodies, sneakers, workwear, and sizing.",
      ko: "A short checklist for winter coats, hoodies, sneakers, workwear, and sizing.",
    },
  },
  {
    id: "daegu-food-map",
    citySlug: "daegu",
    category: "food",
    title: {
      uz: "Daeguda arzon ovqat",
      ru: "Budget food in Daegu",
      en: "Budget food in Daegu",
      ko: "Budget food in Daegu",
    },
    summary: {
      uz: "Talaba va ishchilar uchun tez, arzon va yaqin variantlar.",
      ru: "Fast, nearby options for students and workers.",
      en: "Fast, nearby options for students and workers.",
      ko: "Fast, nearby options for students and workers.",
    },
  },
];
